# python-scripts
Python utilities - compatible with Python 3.5 and above.

Notes:
1. If the hash match fails for any file when running the restore.py script, more warning should be given. 
At present, there is just a flag reported in backup_info.txt.
